# Generated by Django 5.0.7 on 2024-08-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo_created_at_userinfo_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_methods', models.JSONField(blank=True, null=True)),
                ('event_preferences', models.JSONField(default=dict)),
                ('membership_status', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_details', models.JSONField(blank=True, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('recent_login_activity', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
